Fix arrow properties for 1.14
unizenscript/Denizen-For-Bukkit pull request #1
Opened 2019-06-10 04:45 UTC by MusicScore

Also added some tipped arrow methods to the ArrowHelper interface in preparation for the eventual addition of tipped arrow properties.

2019-07-02 16:11 UTC, Morphan1 requested changes
Just a couple of minor things

2019-07-02 16:11 UTC, Morphan1 commented on plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityCritical.java
> +        return String.valueOf(NMSHandler.getInstance().getArrowHelper().isCritical(entity.getBukkitEntity()));
If this is false, the method should return null rather than `"false"`

2019-07-02 16:11 UTC, Morphan1 commented on plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityCritical.java
> +        // @mechanism dEntity.entity
I don't think this is the right mechanism

2019-08-16 04:15 UTC, MusicScore commented
Changes were made, plus some corrective edits were made to match with the upstream (at the time of the force push).

2019-08-16 04:21 UTC, Morphan1 approved these changes

2019-08-31 14:08 UTC, MusicScore commented
Additional force push to resolve upstream errors from the recent commits.

2019-08-31 20:02 UTC, BlackCoyote approved these changes

2019-08-31 22:58 UTC, merged